drinks/urls.py
from django.urls import path
from .views import show_drink, drink_detail, add_drink, get_drink, get_drink_by_id, filter_drink, add_to_favorites, show_json, show_json_by_id, add_to_fav_flutter

app_name = 'drinks'

urlpatterns = [
    path('', show_drink, name='show_drink'),
    path('drink_detail/<int:drink_id>/', drink_detail, name='drink_detail'),
    path('add_drink/', add_drink, name='add_drink'),
    path('get_drink/', get_drink, name='get_drink'),
    path('get_drink/<int:id>/', get_drink_by_id, name="get_drink_by_id"),
    path('filter_drink/', filter_drink, name='filter_drink'),
    path('add_to_favorites/<int:drink_id>', add_to_favorites, name='add_to_favorites'),
    path("json/", show_json, name="show_json"),
    path("json/<int:id>", show_json_by_id, name="show_json_by_id"),
    path("add_to_fav_flutter/<int:drink_id>/<int:user_id>/", add_to_fav_flutter, name="add_to_fav_flutter")
]

favfnd/urls.py
from django.urls import path
from favfnd.views import show_favorites, show_favfood, show_favdrink, filter_foods, filter_drink, show_json_favfood_by_user_id, show_json_favdrink_by_user_id, remove_favdrink, remove_favfood

app_name = 'favfnd'

urlpatterns = [
    path('', show_favorites, name='show_favorites'),
    path("food/", show_favfood, name="show_favfood"),
    path('food/filter_foods/', filter_foods, name='filter_foods'),
    path("drink/", show_favdrink, name="show_favdrink"),
    path('drink/filter_drink/', filter_drink, name='filter_drink'),
    path("get-favfood/<int:user_id>/", show_json_favfood_by_user_id, name="show_json_favfood_by_user_id"),
    path("get-favdrink/<int:user_id>/", show_json_favdrink_by_user_id, name="show_json_favdrink_by_user_id"),
    path('remove-drink/<int:drink_id>/', remove_favdrink, name='remove_favdrink'),
    path('remove-food/<int:food_id>/', remove_favfood, name='remove_favfood'),
]

foods/urls.py
from django.urls import path
from .views import show_food, food_detail, add_food, get_food, get_food_by_id, filter_foods, add_to_favorites, show_json, show_json_by_id, add_to_fav_flutter

app_name = 'foods'

urlpatterns = [
    path('', show_food, name='show_food'),
    path('food_detail/<int:food_id>/', food_detail, name='food_detail'),
    path('add_food/', add_food, name='add_food'),
    path('get_food/', get_food, name='get_food'),
    path('get_food/<int:id>/', get_food_by_id, name="get_food_by_id"),
    path('filter_foods/', filter_foods, name='filter_foods'),
    path('add_to_favorites/<int:food_id>/', add_to_favorites, name='add_to_favorites'),
    path("json/", show_json, name="show_json"),
    path("add_to_fav_flutter/<int:food_id>/<int:user_id>/", add_to_fav_flutter, name="add_to_fav_flutter")
]

recommended/urls.py
from django.urls import path
from recommended.views import show_page, show_food_json

app_name = 'recommended'

urlpatterns = [
    path('', show_page, name='show_page'),
    path("show_food_json/", show_food_json, name="show_food_json")

]

reviews/urls.py
from django.urls import path
from .views import review_fnd, get_reviews_json,food_detail, drink_detail, get_reviews_template, reviews_template, get_all_reviews_partial, review_fnd_ajax, get_all_reviews_json, get_csrf_token_ajax, review_fnd_flutter, food_review_detail, drink_review_detail

app_name = "reviews"

urlpatterns = [
    path('food_detail/<int:food_id>/', food_detail, name='food_detail'),
    path('food_detail/<int:food_id>/reviews/', food_review_detail, name='review_detail'),
    path('drink_detail/<int:drink_id>/', drink_detail, name='drink_detail'),
    path('drink_detail/<int:food_id>/reviews/', drink_review_detail, name='review_detail'),
    path('get_template', reviews_template, name='get_template'),
    path('get_reviews_template', get_all_reviews_partial, name='get_reviews_template'),
    path('get_all_reviews_json', get_all_reviews_json, name='get_all_reviews_json'),
    path('<str:content_type>/<int:object_id>/review_fnd', review_fnd, name='review_fnd'),
    path('<str:content_type>/<int:object_id>/review_fnd_ajax', review_fnd_ajax, name='review_fnd_ajax'),
    path('<str:content_type>/<int:object_id>/review_fnd_flutter', review_fnd_flutter, name='review_fnd_flutter'),
    path('<str:content_type>/<int:object_id>/get_reviews_json', get_reviews_json, name='get_reviews_json'),
    path('<str:content_type>/<int:object_id>/get_reviews_template', get_reviews_template, name='get_reviews_template'),
    path('get_csrf_token_reviews', get_csrf_token_ajax, name='get_csrf_token_reviews'),
]

sibuk/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user_auth/', include('user_auth.urls')),
    path('reviews/', include("reviews.urls")),  
    path('', include('recommended.urls')),
    path('favorites/', include('favfnd.urls')),
    path('api/foods/', include('foods.urls')),
    path('api/drinks/', include('drinks.urls'))
    ]

recommended/models.py
from django.db import models

recommended/forms.py
from django import forms

class FavoriteFilter(forms.Form):
    type = forms.CharField(required=False, widget=forms.TextInput(attrs={'placeholder': 'Food/Drinks'}))

recommended/views.py
from django.shortcuts import render, redirect
from foods.models import Food
from drinks.models import Drink
from foods.views import food_detail
from django.http import HttpResponse
from django.core import serializers
from django.urls import reverse
from .forms import FavoriteFilter
import random
# Create your views here.

def show_page (request):
    food_items = list(Food.objects.all())
    drink_items = list(Drink.objects.all())
    form = FavoriteFilter(request.GET)


    random_food_items = random.sample(food_items, 6)
    random_drink_items = random.sample(drink_items, 6)


    data_for_food = []
    data_for_drink = []

    for food in random_food_items:
        food_data = serializers.serialize('python', [food])[0]
        data_for_food.append(food_data)

    for drink in random_drink_items:
        drink_data = serializers.serialize('python', [drink])[0]
        data_for_drink.append(drink_data)

    
    context = {
        'food': data_for_food,
        'drink': data_for_drink
    }
    
    if form.is_valid() :
        type = form.cleaned_data.get("type")
        if type == "Foods" :
            context = {
                'food': data_for_food
            }
        elif type == "Drinks" :
            context = {
                'drink': data_for_drink
            }
        else :
             context = {
                'food': data_for_food,
                'drink': data_for_drink
            }    
    return render(request, 'index.html', context)



def show_food_json(request):
    data = list(Food.objects.all())
    random_items = random.sample(data, 6)
    return HttpResponse(serializers.serialize("json", random_items), content_type="application/json")

recommended/templates/index.html
{% extends 'base.html' %} {% load static %} {% block meta %}
<title>Home | Dracarys</title>
{% endblock meta %} {% block content %}
<!-- Hero Section -->
<main
  class="hero-container mx-auto py-4"
>
  <section class="hero-image-container">
    <img src="static/images/hero.png" class="block hero-image" />
  </section>
  <section class="hero-content-container">
    <h2 class="hero-title">Enhance your culinary experience,</h2>
    <h2 class="hero-title">with Dracarys</h2>
    <div class="hero-items d-flex gap-3 mt-4 mx-auto">
      <div class="text-center d-flex flex-column" style="width: fit-content">
        <span  class="hero-item-icon">
          <i class="fa-solid fa-bowl-food"></i>
        </span>
        <div>
          <div class="hero-item-desc">A lot of food</div>
          <div class="hero-item-desc">recommendation</div>
        </div>
      </div>
      <div class="text-center d-flex flex-column" style="width: fit-content">
        <span  class="hero-item-icon">
          <i class="fa-solid fa-mug-hot"></i>
        </span>
        <div>
          <div class="hero-item-desc">Find your favorite</div>
          <div class="hero-item-desc">drinks</div>
        </div>
      </div>
      <div class="text-center d-flex flex-column" style="width: fit-content">
        <span  class="hero-item-icon">
          <i class="fa-solid fa-star"></i>
        </span>
        <div>
          <div class="hero-item-desc">Give your</div>
          <div class="hero-item-desc">reviews</div>
        </div>
      </div>
    </div>
  </section>
</main>

<!-- Features Section -->
<section class="features-container container-fluid my-4">
  <h2 class="hero-title text-center py-4">Our Features</h2>
  <div
    class="features-items d-flex flex-wrap gap-4 text-center justify-content-center mt-4"
  >
    <a class="p-4 feature-item shadow-sm position-relative" href="{% url 'foods:show_food' %}">
      <div class="feature-item-img">
        <img src="static/images/food.png" alt="" class="food-img" />
      </div>
      <div class="feature-item-desc">
        <h3 class="feature-title">Food Catalogue</h3>
        <div class="features-desc">Explore delicious food</div>
      </div>
    </a>
    <a class="p-4 feature-item shadow-sm position-relative" href="{% url 'drinks:show_drink' %}">
      <div class="feature-item-img">
        <img src="static/images/drinks.png" alt="" class="drinks-img" />
      </div>
      <div class="feature-item-desc">
        <h3 class="feature-title">Drink Catalogue</h3>
        <p class="features-desc">Find all fresh drinks</p>
      </div>
    </a>
    <a class="p-4 feature-item shadow-sm position-relative" href="{% url 'favfnd:show_favorites' %}">
      <div class="feature-item-img">
        <img src="static/images/favorites.png" alt="" class="favorites-img" />
      </div>
      <div class="feature-item-desc">
        <h3 class="feature-title">Favorites</h3>
        <p class="features-desc">Add to favorites</p>
      </div>
    </a>
    <a class="p-4 feature-item shadow-sm position-relative" href="{% url 'reviews:get_template' %}">
      <div class="feature-item-img feature-item-reviews">
        <img src="static/images/reviews.png" alt="" class="reviews-img" />
      </div>
      <div class="feature-item-desc">
        <h3 class="feature-title">Reviews</h3>
        <div class="features-desc">Give your review</div>
      </div>
    </a>
  </div>
</section>

<!-- Recommended Section -->
<section class="recommended-container container-fluid">
  <h2 class="hero-title text-center">Explore Our Recommendation</h2>
  <div>
    <div class="filter-box">
      <form
        id="filterForm"
        class="filter-form"
        method="GET"
      >
        <button type="submit" class="filter-btn" name="type" value="Foods">
          <img src="{% static "images/category/rice_icon.png" %}" class="filter-img" alt="">
          <span>Foods</span>
        </button>
        <button type="submit" class="filter-btn" name="type" value="Drinks">
          <img src="{% static "images/category/coffe_icon.png" %}" class="filter-img" alt="">
          <span>Drinks</span>
        </button>
        <button type="submit" class="filter-btn" name="" value="">
          <img src="{% static "images/category/no_filter_food.png" %}" class="filter-img" alt="">
          <span>Remove Filter</span>
        </button>
      </form>
    </div>
    <div class="card-container m-4 p-4 d-flex flex-wrap gap-4 justify-content-center">
      {% for foodItem in food %}
      <!-- #### Card Item #### -->
      <div class="card-box">
        <div class="card-box-inner shadow-sm">
          <div class="card-box-front d-flex gap-4">
            <img
            {% if foodItem.fields.category == "Nasi"  %}
                src="{% static  'images/category/rice_icon.png' %}"
            {% elif foodItem.fields.category == "Mie"  %}
                src="{% static  'images/category/noodle_icon.png' %}"
            {% elif foodItem.fields.category == "Snack"  %}
                src="{% static  'images/category/snack_icon.png' %}"
            {% elif foodItem.fields.category == "Lainnya"  %}
                src="{% static  'images/category/other_icon.png' %}"
            {% endif %}
              src="{% static  'images/card-decoration.jpg' %}"
              class="card-decoration"
              alt="card-decoration"
            />
            <div class="card-box-description">
              <h5 class="card-box-title mt-4" >{{ foodItem.fields.product.title|truncatewords:3 }}</h5>
              <div>
                <p>{{ foodItem.fields.calories}} kcal</p>
                <p>{{ foodItem.fields.merchant_name.title|truncatewords:2 }}</p>
              </div>
              <div class="relative">
                <a href="{% url 'foods:food_detail' foodItem.pk %}" class="btn-custom" style="background-color: #014d2f;">
                    See Details
                </a>
              </div>
            </div>
          </div>
        </div>
      </div>
      {% endfor %}
      <!-- #### Card Item #### -->
      {% for drinkItem in drink %}
      <!-- #### Card Item #### -->
      <div class="card-box">
        <div class="card-box-inner shadow-sm">
          <div class="card-box-front d-flex gap-4">
            <img
            {% if  drinkItem.fields.category == "Kopi" %}
              src="{% static  'images/category/coffe_icon.png' %}"
            {% else %}
              src="{% static 'images/category/non_coffee_icon.png' %}"
            {% endif %}
              src="{% static  'images/card-decoration.jpg' %}"
              class="card-decoration"
              alt="card-decoration"
            />
            <div class="card-box-description">
              <h5 class="card-box-title mt-4">{{ drinkItem.fields.product.title|truncatewords:3 }}</h5>
              <div>
                <p>{{ drinkItem.fields.calories }} kcal</p>
                <p>{{ drinkItem.fields.merchant_name.title }}</p>
              </div>
              <div class="relative">
                <a href="{% url 'drinks:drink_detail' drinkItem.pk %}" class="btn btn-success" style="background-color: #014d2f;">
                    See Details
                </a>
              </div>
            </div>
          </div>
        </div>
      </div>
      {% endfor %}
      <!-- #### Card Item #### -->
    </div>
  </div>
    
  </div>
</section>

{% endblock content %}