foods/urls.py
from django.urls import path
from .views import show_food, food_detail, add_food, get_food, get_food_by_id, filter_foods, add_to_favorites, show_json, show_json_by_id, add_to_fav_flutter

app_name = 'foods'

urlpatterns = [
    path('', show_food, name='show_food'),
    path('food_detail/<int:food_id>/', food_detail, name='food_detail'),
    path('add_food/', add_food, name='add_food'),
    path('get_food/', get_food, name='get_food'),
    path('get_food/<int:id>/', get_food_by_id, name="get_food_by_id"),
    path('filter_foods/', filter_foods, name='filter_foods'),
    path('add_to_favorites/<int:food_id>/', add_to_favorites, name='add_to_favorites'),
    path("json/", show_json, name="show_json"),
    path("add_to_fav_flutter/<int:food_id>/<int:user_id>/", add_to_fav_flutter, name="add_to_fav_flutter")
]

reviews/urls.py
from django.urls import path
from .views import review_fnd, get_reviews_json,food_detail, drink_detail, get_reviews_template, reviews_template, get_all_reviews_partial, review_fnd_ajax, get_all_reviews_json, get_csrf_token_ajax, review_fnd_flutter, food_review_detail, drink_review_detail

app_name = "reviews"

urlpatterns = [
    path('food_detail/<int:food_id>/', food_detail, name='food_detail'),
    path('food_detail/<int:food_id>/reviews/', food_review_detail, name='review_detail'),
    path('drink_detail/<int:drink_id>/', drink_detail, name='drink_detail'),
    path('drink_detail/<int:food_id>/reviews/', drink_review_detail, name='review_detail'),
    path('get_template', reviews_template, name='get_template'),
    path('get_reviews_template', get_all_reviews_partial, name='get_reviews_template'),
    path('get_all_reviews_json', get_all_reviews_json, name='get_all_reviews_json'),
    path('<str:content_type>/<int:object_id>/review_fnd', review_fnd, name='review_fnd'),
    path('<str:content_type>/<int:object_id>/review_fnd_ajax', review_fnd_ajax, name='review_fnd_ajax'),
    path('<str:content_type>/<int:object_id>/review_fnd_flutter', review_fnd_flutter, name='review_fnd_flutter'),
    path('<str:content_type>/<int:object_id>/get_reviews_json', get_reviews_json, name='get_reviews_json'),
    path('<str:content_type>/<int:object_id>/get_reviews_template', get_reviews_template, name='get_reviews_template'),
    path('get_csrf_token_reviews', get_csrf_token_ajax, name='get_csrf_token_reviews'),
]

sibuk/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user_auth/', include('user_auth.urls')),
    path('reviews/', include("reviews.urls")),  
    path('', include('recommended.urls')),
    path('favorites/', include('favfnd.urls')),
    path('api/foods/', include('foods.urls')),
    path('api/drinks/', include('drinks.urls'))
    ]

reviews/models.py
from django.db import models
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator

class Review(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    rating = models.IntegerField(
        validators=[
            MaxValueValidator(5),
            MinValueValidator(1)
        ])
    ulasan = models.TextField()
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')

reviews/forms.py
from django.forms import ModelForm, TextInput
from .models import Review

class ReviewForm(ModelForm):
    class Meta:
        model = Review
        fields = "__all__"
        exclude = ("user", "object_id", "content_type")

reviews/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseBadRequest, HttpResponseRedirect, JsonResponse
from django.contrib.contenttypes.models import ContentType
from django.contrib.auth.decorators import login_required
from django.core import serializers
from django.urls import reverse
from django.db.models import Count, Avg
from django.template.loader import render_to_string
from django.middleware.csrf import get_token
from django.views.decorators.csrf import csrf_exempt
import json

from .models import Review
from .forms import ReviewForm
from foods.models import Food
from drinks.models import Drink

@login_required(login_url='/user_auth/login')
def review_fnd(request, content_type, object_id):
    content_type = ContentType.objects.get(model=content_type)
    if content_type.model == 'food':
        obj = get_object_or_404(Food, pk=object_id)
    elif content_type.model == 'drink':
        obj = get_object_or_404(Drink, pk=object_id)
    else:
        return HttpResponseBadRequest("Invalid content type")

    if request.method == 'POST':
        rating = request.POST.get('rating')
        ulasan = request.POST.get('ulasan')
        Review.objects.create(
            user = request.user,
            rating=rating,
            ulasan=ulasan,
            content_type=content_type,
            object_id=object_id
        )
        if content_type.model == 'food':
            return HttpResponseRedirect(reverse('foods:show_food'))
        else:
            return HttpResponseRedirect(reverse('drinks:show_drink'))
    form = ReviewForm()
    return render(request, 'review_form.html', {'object': obj, 'form':form})

def review_fnd_ajax(request, content_type, object_id):
    content_type = ContentType.objects.get(model=content_type)
    if content_type.model not in ['food', 'drink']:
        return HttpResponseBadRequest("Invalid content type")
    
    if request.method == 'POST':
        if request.user.is_authenticated:
            rating = request.POST.get('rating')
            ulasan = request.POST.get('ulasan')
            Review.objects.create(
                user=request.user,
                rating=rating,
                ulasan=ulasan,
                content_type=content_type,
                object_id=object_id
            )
           
            if content_type.model == 'food':
                return JsonResponse({'success': True, 'redirect_url': reverse('foods:show_food')})
            else:
                return JsonResponse({'success': True, 'redirect_url': reverse('drinks:show_drink')})
        else:
            return JsonResponse({'success': False, 'login_required': True})

    return JsonResponse({'success': False, 'error': 'Invalid request method'})

def food_detail(request, food_id):
    food = get_object_or_404(Food, id=food_id)
    food_content_type = ContentType.objects.get_for_model(Food)
    reviews = Review.objects.filter(
        content_type=food_content_type,
        object_id=food_id
    ).select_related('user')  

    context = {
        'food': food,
        'reviews': reviews
    }
    return render(request, 'reviews/food_detail.html', context)

def food_review_detail(request, food_id):
    food_content_type = ContentType.objects.get_for_model(Food)
    reviews = Review.objects.filter(
        content_type=food_content_type,
        object_id=food_id
    ).select_related('user')  
    context = {
        'reviews': reviews,
        'food_id': food_id,
    }
    return render(request, 'review_detail.html', context)

def drink_detail(request, drink_id):
    drink = get_object_or_404(Drink, id=drink_id)
    drink_content_type = ContentType.objects.get_for_model(Drink)
    reviews = Review.objects.filter(
        content_type= drink_content_type,
        object_id=drink_id
    ).select_related('user')  

    context = {
        'drink': drink,
        'reviews': reviews
    }
    return render(request, 'reviews/drink_detail.html', context)

def drink_review_detail(request, drink_id):
    drink_content_type = ContentType.objects.get_for_model(Drink)
    reviews = Review.objects.filter(
        content_type=drink_content_type,
        object_id=drink_id
    ).select_related('user')  
    context = {
        'reviews': reviews,
        'drink_id': drink_id,
    }
    return render(request, 'review_detail.html', context)

    
@csrf_exempt
def review_fnd_flutter(request, content_type, object_id):
    content_type = ContentType.objects.get(model=content_type)
    if (content_type.model != 'food') and (content_type.model == 'drink'):
        return JsonResponse({'success': False})
    
    if request.method == 'POST':
        if request.user.is_authenticated:
            try:
                data = json.loads(request.body)
                rating = data.get('rating')
                ulasan = data.get('ulasan')

                if not (rating and ulasan):
                    return JsonResponse({'success': False, 'error': 'Missing rating or ulasan'})

                Review.objects.create(
                    user=request.user,
                    rating=rating,
                    ulasan=ulasan,
                    content_type=content_type,
                    object_id=object_id
                )
                return JsonResponse({'success': True}, status=200)
            except json.JSONDecodeError:
                return JsonResponse({'success': False, 'error': 'Invalid JSON data'}, status=300)
            except Exception as e:
                return JsonResponse({'success': False, 'error': str(e)}, status=300)
        else:
            return JsonResponse({'success': False, 'login_required': True}, status=403)

    return JsonResponse({'success': False, 'error': 'Invalid request method'}, status=404)

def get_csrf_token_ajax(request):
    csrf_token = get_token(request)
    return JsonResponse({'csrf_token': csrf_token})

def get_reviews_json(request, content_type, object_id):
    content_type = ContentType.objects.get(model=content_type)
    if content_type.model == 'food':
        obj = get_object_or_404(Food, pk=object_id)
    elif content_type.model == 'drink':
        obj = get_object_or_404(Drink, pk=object_id)
    else:
        return HttpResponseBadRequest("Invalid content type")
    reviews = Review.objects.filter(content_type=content_type, object_id=object_id)
    reviews_data = serializers.serialize('json', reviews)
    return JsonResponse({'reviews': reviews_data}, safe=False)

def get_reviews_template(request, content_type, object_id):
    content_type = ContentType.objects.get(model=content_type)
    if content_type.model == 'food':
        obj = get_object_or_404(Food, pk=object_id)
    elif content_type.model == 'drink':
        obj = get_object_or_404(Drink, pk=object_id)
    else:
        return HttpResponseBadRequest("Invalid content type")
    reviews = Review.objects.filter(content_type=content_type, object_id=object_id)
    return render(request, 'fnd_reviews.html', {'reviews': reviews})


def reviews_template(request):
    return render(request, 'all_reviews.html')

def get_all_reviews_partial(request):
    data = []
    foods = Food.objects.prefetch_related('reviews').annotate(num_reviews=Count('reviews')).all()
    for food in foods:
        food_data = serializers.serialize('python', [food])[0]
        food_data['type'] = 'food'
        food_data['fields']['average_rating'] = food.reviews.aggregate(avg_rating=Avg('rating'))['avg_rating'] or 0
        food_data['fields']['percentage_rating'] = food_data['fields']['average_rating']/5*100
        food_data['fields']['num_reviews'] = food.num_reviews
        data.append(food_data)
    drinks = Drink.objects.prefetch_related('reviews').annotate(num_reviews=Count('reviews')).all()
    for drink in drinks:
        drink_data = serializers.serialize('python', [drink])[0]
        drink_data['type'] = 'drink'
        drink_data['fields']['average_rating'] = drink.reviews.aggregate(avg_rating=Avg('rating'))['avg_rating'] or 0
        drink_data['fields']['percentage_rating'] = drink_data['fields']['average_rating']/5*100
        drink_data['fields']['num_reviews'] = drink.num_reviews
        data.append(drink_data)
    sort_by = request.GET.get('sort_by')
    if sort_by == 'rating':
        data.sort(key=lambda x: x['fields']['average_rating'] or 0, reverse=True)
    elif sort_by == 'reviews':
        data.sort(key=lambda x: x['fields']['num_reviews'], reverse=True)

    # Render the template with the data
    html_content = render_to_string('partial_all_reviews.html', {'data': data})
    return JsonResponse({'html_content': html_content})

def get_all_reviews_json(request):
    data = []
    foods = Food.objects.prefetch_related('reviews').annotate(num_reviews=Count('reviews')).all()
    for food in foods:
        food_data = serializers.serialize('python', [food])[0]
        food_data['type'] = 'food'
        food_data['fields']['average_rating'] = food.reviews.aggregate(avg_rating=Avg('rating'))['avg_rating'] or 0
        food_data['fields']['percentage_rating'] = food_data['fields']['average_rating']/5*100
        food_data['fields']['num_reviews'] = food.num_reviews
        data.append(food_data)
    drinks = Drink.objects.prefetch_related('reviews').annotate(num_reviews=Count('reviews')).all()
    for drink in drinks:
        drink_data = serializers.serialize('python', [drink])[0]
        drink_data['type'] = 'drink'
        drink_data['fields']['average_rating'] = drink.reviews.aggregate(avg_rating=Avg('rating'))['avg_rating'] or 0
        drink_data['fields']['percentage_rating'] = drink_data['fields']['average_rating']/5*100
        drink_data['fields']['num_reviews'] = drink.num_reviews
        data.append(drink_data)

    sort_by = request.GET.get('sort_by')
    if sort_by == 'rating':
        data.sort(key=lambda x: x['fields']['average_rating'] or 0, reverse=True)
    elif sort_by == 'reviews':

reviews/templates/all_reviews.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="flex container items-center align-center mx-auto flex-col mt-4">
    <div class="grid grid-cols-2 md:grid-cols-5 gap-4 px-4 md:px-0"></div>
        <select id="sort-by-dropdown">
            <option value="reviews">Sort by Number of Reviews</option>
            <option value="rating">Sort by Rating</option>
        </select>
    </div>
    <div id="review-container" class="d-flex flex-wrap gap-4 justify-content-center mt-4 mb-4">
        <!-- Will be filled with partial html -->
    </div>
</div>

<script>
    $(document).ready(function() {
        // Function to fetch and render reviews based on sorting criteria
        function fetchReviews(sortBy) {
            $.ajax({
                url: "{% url 'reviews:get_reviews_template' %}",
                method: "GET",
                data: {sort_by: sortBy},
                dataType: 'json',
                success: function(response) {
                    $("#review-container").html(response.html_content);
                }
            });
        }

        // Event listener for dropdown change
        $("#sort-by-dropdown").change(function() {
            var selectedSortBy = $(this).val();
            fetchReviews(selectedSortBy);
        });

        fetchReviews("reviews");
    });
</script>

{% endblock content %}

reviews/templates/fnd_reviews.html
{% extends 'base.html' %} 
{% load static %}
{% block content %}

<div class="grid grid-cols-2 md:grid-cols-5 gap-4 px-4 md:px-0">
    {% for review in reviews %}
        <div class="max-w-md rounded overflow-hidden shadow-lg bg-white relative border">
            <div class="px-4 md:px-6 py-4">
                <div class="md:text-xl text-[#005b9c] font-inter font-bold mb-2">
                    Rating: {{ review.rating }}
                </div>
                <div class="text-sm md:text-gray-600 mb-2">
                    Review: {{ review.ulasan }}
                </div>
            </div>
        </div>
    {% endfor %}
    </div>

{% endblock content %}

reviews/templates/partial_all_reviews.html
{% load static %}
<link rel="stylesheet" href="{% static 'reviews/css/star.css' %}">
{% for item in data %}
    <div class="card-box">
        <div class="card-box-inner shadow-sm">
            <div class="card-box-front d-flex gap-4">
                <img
                {% if item.fields.category == "Nasi"  %}
                    src="{% static  'images/category/rice_icon.png' %}"
                {% elif item.fields.category == "Mie"  %}
                    src="{% static  'images/category/noodle_icon.png' %}"
                {% elif item.fields.category == "Snack"  %}
                    src="{% static  'images/category/snack_icon.png' %}"
                {% elif item.fields.category == "Lainnya"  %}
                    src="{% static  'images/category/other_icon.png' %}"
                {% elif  item.fields.category == "Kopi" %}
            	    src="{% static  'images/category/coffe_icon.png' %}"
                {% else %}
                    src="{% static 'images/category/non_coffee_icon.png' %}"
                {% endif %}
                class="card-decoration"
                alt="card-decoration"
                />
                <div class="card-box-description">
                    <div class="stars-landing" id="stars-box" style="--rating: {{ item.fields.average_rating }};">★★★★★</div>
                    <h5 class="card-title">{{ item.fields.num_reviews }} reviews</h5>
                    <h5 class="card-box-title mt-4" style="font-size: 1.25rem;">{{ item.fields.product.title|truncatewords:2 }}</h5>
                    <div class="relative">
                        {% if item.type == 'food' %}
                        <a href="{% url 'reviews:food_detail' item.pk %}" class="btn btn-success" >
                            See Details
                        </a>
                        {% elif item.type == 'drink' %}
                        <a href="{% url 'reviews:drink_detail' item.pk %}" class="btn btn-success" >
                            See Details
                        </a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endfor %}

reviews/templates/review_detail.html
{% load static %}
<link rel="stylesheet" href="{% static 'reviews/css/star.css' %}">

<div style="margin-bottom: 5em; position: relative; padding: 1.5em; margin-right: auto !important; margin-left: auto !important; max-width: 650px;">
    <h4>Reviews</h4>
    {% if reviews %}
        <div class="review-list">
            {% for review in reviews %}
                <div class="row review-item mt-3">
                    <div class="col-auto align-self-center">
                        <i class="fa-solid fa-user detail-desc-icon"></i>
                    </div>
                    <div class="col" style="padding: 5px;  display: flex; flex-direction: column; flex-wrap: wrap; align-items: flex-start; text-align: center; background-color: rgb(245, 255, 235);">
                        <p style="font-weight: bold; margin: 0px;"><strong>{{ review.user.username }}</strong></p>
                        <div class="stars-landing" id="stars-box" style="--rating: {{ review.rating }}; margin-top: -30px;">★★★★★</div>
                        <div style="margin: 0px;">
                            <p class="desc-text" style="margin: 0;">{{ review.ulasan }}</p>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% else %}
        <p class="text-muted text-center mt-3">No reviews yet. Be the first to review!</p>
    {% endif %}
</div>

reviews/templates/review_form.html
{% extends 'base.html' %} 
{% load static %}

{% block meta %}
<title>Review</title>
<link rel="stylesheet" href="{% static 'reviews/css/rating.css' %}">
{% endblock meta %} 

{% block content %}
<form id="review-form" method="post">
  {% csrf_token %}
  <div class="rating">
    <span class="star" data-value="1">&#9733;</span>
    <span class="star" data-value="2">&#9733;</span>
    <span class="star" data-value="3">&#9733;</span>
    <span class="star" data-value="4">&#9733;</span>
    <span class="star" data-value="5">&#9733;</span>
    <input type="hidden" id="id_rating" name="rating">
  </div>
  <div class="form-group">
    <label for="id_ulasan">Review:</label>
    <textarea class="form-control" id="id_ulasan" name="ulasan" rows="3"></textarea>
  </div>
  <button type="submit" class="btn btn-outline-success">Submit Review</button>
</form>

{% if messages %}
<ul>
  {% for message in messages %}
  <li>{{ message }}</li>
  {% endfor %}
</ul>
{% endif %}

<script>
  $(document).ready(function() {
    $('.star').click(function() {
      // Update the hidden input field with the selected rating value
      $('#id_rating').val($(this).data('value'));
      // Update the UI to reflect the selected rating
      $(this).addClass('selected');
      $(this).prevAll().addClass('selected');
      $(this).nextAll().removeClass('selected');
    });
  });
</script>

{% endblock content %}

reviews/templates/review_modal.html
{% load static %}
<link rel="stylesheet" href="{% static 'reviews/css/rating.css' %}">
<div class="modal-content">
    <!-- Modal Header -->
    <div class="modal-header">
      <h4 class="modal-title">Write a Review</h4>
      <button type="button" class="close" data-dismiss="modal">&times;</button>
    </div>
  
    <!-- Modal Body -->
    <div class="modal-body">
      <form id="review-form" method="post">
        {% csrf_token %}
        <div class="rating">
          <span class="star" data-value="1">&#9733;</span>
          <span class="star" data-value="2">&#9733;</span>
          <span class="star" data-value="3">&#9733;</span>
          <span class="star" data-value="4">&#9733;</span>
          <span class="star" data-value="5">&#9733;</span>
          <input type="hidden" id="id_rating" name="rating">
        </div>
        <div class="form-group">
          <label for="id_ulasan">Review:</label>
          <textarea class="form-control" id="id_ulasan" name="ulasan" rows="3"></textarea>
        </div>
        <button type="submit" class="btn btn-outline-success">Submit Review</button>
      </form>
    </div>
  
    <!-- Modal Footer -->
    <div class="modal-footer">
      <button id="close-modal" type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
    </div>
</div>

<script>
  $(document).ready(function() {
    $('.star').click(function() {
      // Update the hidden input field with the selected rating value
      $('#id_rating').val($(this).data('value'));
      // Update the UI to reflect the selected rating
      $(this).addClass('selected');
      $(this).prevAll().addClass('selected');
      $(this).nextAll().removeClass('selected');
    });
  });
</script>
  