drinks/urls.py
from django.urls import path
from .views import show_drink, drink_detail, add_drink, get_drink, get_drink_by_id, filter_drink, add_to_favorites, show_json, show_json_by_id, add_to_fav_flutter

app_name = 'drinks'

urlpatterns = [
    path('', show_drink, name='show_drink'),
    path('drink_detail/<int:drink_id>/', drink_detail, name='drink_detail'),
    path('add_drink/', add_drink, name='add_drink'),
    path('get_drink/', get_drink, name='get_drink'),
    path('get_drink/<int:id>/', get_drink_by_id, name="get_drink_by_id"),
    path('filter_drink/', filter_drink, name='filter_drink'),
    path('add_to_favorites/<int:drink_id>', add_to_favorites, name='add_to_favorites'),
    path("json/", show_json, name="show_json"),
    path("json/<int:id>", show_json_by_id, name="show_json_by_id"),
    path("add_to_fav_flutter/<int:drink_id>/<int:user_id>/", add_to_fav_flutter, name="add_to_fav_flutter")
]

favfnd/urls.py
from django.urls import path
from favfnd.views import show_favorites, show_favfood, show_favdrink, filter_foods, filter_drink, show_json_favfood_by_user_id, show_json_favdrink_by_user_id, remove_favdrink, remove_favfood

app_name = 'favfnd'

urlpatterns = [
    path('', show_favorites, name='show_favorites'),
    path("food/", show_favfood, name="show_favfood"),
    path('food/filter_foods/', filter_foods, name='filter_foods'),
    path("drink/", show_favdrink, name="show_favdrink"),
    path('drink/filter_drink/', filter_drink, name='filter_drink'),
    path("get-favfood/<int:user_id>/", show_json_favfood_by_user_id, name="show_json_favfood_by_user_id"),
    path("get-favdrink/<int:user_id>/", show_json_favdrink_by_user_id, name="show_json_favdrink_by_user_id"),
    path('remove-drink/<int:drink_id>/', remove_favdrink, name='remove_favdrink'),
    path('remove-food/<int:food_id>/', remove_favfood, name='remove_favfood'),
]

foods/urls.py
from django.urls import path
from .views import show_food, food_detail, add_food, get_food, get_food_by_id, filter_foods, add_to_favorites, show_json, show_json_by_id, add_to_fav_flutter

app_name = 'foods'

urlpatterns = [
    path('', show_food, name='show_food'),
    path('food_detail/<int:food_id>/', food_detail, name='food_detail'),
    path('add_food/', add_food, name='add_food'),
    path('get_food/', get_food, name='get_food'),
    path('get_food/<int:id>/', get_food_by_id, name="get_food_by_id"),
    path('filter_foods/', filter_foods, name='filter_foods'),
    path('add_to_favorites/<int:food_id>/', add_to_favorites, name='add_to_favorites'),
    path("json/", show_json, name="show_json"),
    path("add_to_fav_flutter/<int:food_id>/<int:user_id>/", add_to_fav_flutter, name="add_to_fav_flutter")
]

reviews/urls.py
from django.urls import path
from .views import review_fnd, get_reviews_json,food_detail, drink_detail, get_reviews_template, reviews_template, get_all_reviews_partial, review_fnd_ajax, get_all_reviews_json, get_csrf_token_ajax, review_fnd_flutter, food_review_detail, drink_review_detail

app_name = "reviews"

urlpatterns = [
    path('food_detail/<int:food_id>/', food_detail, name='food_detail'),
    path('food_detail/<int:food_id>/reviews/', food_review_detail, name='review_detail'),
    path('drink_detail/<int:drink_id>/', drink_detail, name='drink_detail'),
    path('drink_detail/<int:food_id>/reviews/', drink_review_detail, name='review_detail'),
    path('get_template', reviews_template, name='get_template'),
    path('get_reviews_template', get_all_reviews_partial, name='get_reviews_template'),
    path('get_all_reviews_json', get_all_reviews_json, name='get_all_reviews_json'),
    path('<str:content_type>/<int:object_id>/review_fnd', review_fnd, name='review_fnd'),
    path('<str:content_type>/<int:object_id>/review_fnd_ajax', review_fnd_ajax, name='review_fnd_ajax'),
    path('<str:content_type>/<int:object_id>/review_fnd_flutter', review_fnd_flutter, name='review_fnd_flutter'),
    path('<str:content_type>/<int:object_id>/get_reviews_json', get_reviews_json, name='get_reviews_json'),
    path('<str:content_type>/<int:object_id>/get_reviews_template', get_reviews_template, name='get_reviews_template'),
    path('get_csrf_token_reviews', get_csrf_token_ajax, name='get_csrf_token_reviews'),
]

sibuk/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user_auth/', include('user_auth.urls')),
    path('reviews/', include("reviews.urls")),  
    path('', include('recommended.urls')),
    path('favorites/', include('favfnd.urls')),
    path('api/foods/', include('foods.urls')),
    path('api/drinks/', include('drinks.urls'))
    ]

user_auth/urls.py
from django.urls import path
from .views import register, login_user, logout_user, login_flutter, logout_flutter

app_name = "user_auth"

urlpatterns = [
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('register/', register, name='register'),
    path("login-flutter/", login_flutter, name="login_flutter"),
    path("logout-flutter/", logout_flutter, name="logout_flutter")
]

templates/authenticate_base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% include "head.html" %}
    {% block meta %}
    {% endblock meta %}
  </head>
  <body>
    {% block content %}
    {% endblock content %}
    {% include "base_scripts.html" %}
  </body>
  {% block script %}
  {% endblock script %}
</html>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    {% include "head.html" %}
    {% include "base_scripts.html" %}
    {% block meta %}
    {% endblock meta %}
</head>

<body>
    {% include "navbar.html" %}
    {% block content %}
    {% endblock content %}
    {% include "footer.html" %}


    {% block script %}
    {% endblock script %}
</body>
</html>

templates/base_scripts.html
{% load static %}
<script
  src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
  integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
  crossorigin="anonymous"
></script>
<script
  src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js"
  integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+"
  crossorigin="anonymous"
></script>
<script src="https://kit.fontawesome.com/3846ce632a.js" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

templates/footer.html
{% load static %}
<footer class="container-fluid">
  <div class="container-large p-4 d-flex justify-content-center gap-4">
    <div>
      <div heigth="50">
        <img
        src="{% static 'images/logo1.png' %}"
        alt=""
        class="footer-img"
        width="100"
      />
      </div>
      
      <p class="footer-desc mt-4">
        Dracarys was born from the desire to make it easier for people to find food
        to break their fast. 
      </p>
    </div>
    <div class="ms-4">
      <h5 class="footer-title">Contacts</h5>
      <ul class="footer-list mt-4 d-flex flex-column gap-2">
        <li>
          <span class="me-1"><i class="fa-solid fa-envelope"></i></span>
          <span>help.dracarys@email.com</span>
        </li>
        <li>
          <span class="me-1"><i class="fa-solid fa-phone"></i></span>
          <span>0812 3456 7890</span>
        </li>
      </ul>
    </div>
    <div class="ms-4">
      <h5 class="footer-title">Quick Links</h5>
      <ul class="footer-list mt-4 d-flex flex-column gap-2">
        <li><a href="">Food</a></li>
        <li><a href="">Drinks</a></li>
        <li><a href="">Favorites</a></li>
        <li><a href="">Reviews</a></li>
      </ul>
    </div>
    <div class="ms-4">
      <h5 class="footer-title">Social Media</h5>
      <ul class="footer-list mt-4 d-flex flex-column gap-2">
        <li>
          <span class="me-1 icon-link">
            <i class="fa-brands fa-instagram"></i>
          </span>
          <a href="">Instagram</a>
        </li>
        <li>
          <span class="me-1 icon-link">
            <i class="fa-brands fa-twitter"></i>
          </span>
          <a href="">Twitter</a>
        </li>
        <li>
          <span class="me-1 icon-link">
            <i class="fa-brands fa-github"></i>
          </span>
          <a href="">Github</a>
        </li>
        <li>
          <span class="me-1 icon-link">
            <i class="fa-brands fa-facebook"></i>
          </span>
          <a href="">Facebook</a>
        </li>
      </ul>
    </div>
  </div>
  <p class="text-center copyright-text mt-4">© Copyright Dracarys. All rights reserved.</p>
</footer>

<!-- <i class="fa-brands fa-instagram"></i>
<i class="fa-brands fa-twitter"></i>
<i class="fa-brands fa-github"></i>
<i class="fa-brands fa-facebook"></i> -->

templates/head.html
{% load static %}
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css2?family=PT+Serif:wght@700&display=swap" rel="stylesheet">
<link
  href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
  rel="stylesheet"
  integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
  crossorigin="anonymous"
/>
<script
  src="https://code.jquery.com/jquery-3.6.0.min.js"
  integrity="sha384-KyZXEAg3QhqLMpG8r+J4jsl5c9zdLKaUk5Ae5f5b1bw6AUn5f5v8FZJoMxm6f5cH1"
  crossorigin="anonymous"
></script>
<link rel="stylesheet" href="{% static 'css/style.css' %}">
<link href="/static/images/tabIcon.png" rel="icon">

templates/navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-custom">
  <div class="container-fluid mx-4">
    <a class="navbar-brand" href="{% url 'recommended:show_page' %}">
      <img src="{% static 'images/dark-logo1.png' %}" alt="" width="100" />
    </a>
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarNav"
      aria-controls="navbarNav"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ms-auto">
        <li class="nav-item">
          <a class="nav-link-custom active-custom" aria-current="page" href="{% url 'recommended:show_page' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link-custom" href="{% url 'foods:show_food' %}">Food</a>
        </li>
        <li class="nav-item">
          <a class="nav-link-custom" href="{% url 'drinks:show_drink' %}">Drinks</a>
        </li>
        <li class="nav-item">
          <a class="nav-link-custom" href="{% url 'favfnd:show_favorites' %}">Favorites</a>
        </li>
        <li class="nav-item">
          <a class="nav-link-custom" href="{% url 'reviews:get_template' %}">Reviews</a>
        </li>
      </ul>
      {% if user.is_authenticated %}
      <a href="{% url 'user_auth:logout' %}" class="nav-btn-custom">Logout</a>
      {% else %}
      <a href="{% url 'user_auth:login' %}" class="nav-btn-custom">Login</a>
      {% endif %}
    </div>
  </div>
</nav>