drinks/urls.py
from django.urls import path
from .views import show_drink, drink_detail, add_drink, get_drink, get_drink_by_id, filter_drink, add_to_favorites, show_json, show_json_by_id, add_to_fav_flutter

app_name = 'drinks'

urlpatterns = [
    path('', show_drink, name='show_drink'),
    path('drink_detail/<int:drink_id>/', drink_detail, name='drink_detail'),
    path('add_drink/', add_drink, name='add_drink'),
    path('get_drink/', get_drink, name='get_drink'),
    path('get_drink/<int:id>/', get_drink_by_id, name="get_drink_by_id"),
    path('filter_drink/', filter_drink, name='filter_drink'),
    path('add_to_favorites/<int:drink_id>', add_to_favorites, name='add_to_favorites'),
    path("json/", show_json, name="show_json"),
    path("json/<int:id>", show_json_by_id, name="show_json_by_id"),
    path("add_to_fav_flutter/<int:drink_id>/<int:user_id>/", add_to_fav_flutter, name="add_to_fav_flutter")
]

favfnd/urls.py
from django.urls import path
from favfnd.views import show_favorites, show_favfood, show_favdrink, filter_foods, filter_drink, show_json_favfood_by_user_id, show_json_favdrink_by_user_id, remove_favdrink, remove_favfood

app_name = 'favfnd'

urlpatterns = [
    path('', show_favorites, name='show_favorites'),
    path("food/", show_favfood, name="show_favfood"),
    path('food/filter_foods/', filter_foods, name='filter_foods'),
    path("drink/", show_favdrink, name="show_favdrink"),
    path('drink/filter_drink/', filter_drink, name='filter_drink'),
    path("get-favfood/<int:user_id>/", show_json_favfood_by_user_id, name="show_json_favfood_by_user_id"),
    path("get-favdrink/<int:user_id>/", show_json_favdrink_by_user_id, name="show_json_favdrink_by_user_id"),
    path('remove-drink/<int:drink_id>/', remove_favdrink, name='remove_favdrink'),
    path('remove-food/<int:food_id>/', remove_favfood, name='remove_favfood'),
]

foods/urls.py
from django.urls import path
from .views import show_food, food_detail, add_food, get_food, get_food_by_id, filter_foods, add_to_favorites, show_json, show_json_by_id, add_to_fav_flutter

app_name = 'foods'

urlpatterns = [
    path('', show_food, name='show_food'),
    path('food_detail/<int:food_id>/', food_detail, name='food_detail'),
    path('add_food/', add_food, name='add_food'),
    path('get_food/', get_food, name='get_food'),
    path('get_food/<int:id>/', get_food_by_id, name="get_food_by_id"),
    path('filter_foods/', filter_foods, name='filter_foods'),
    path('add_to_favorites/<int:food_id>/', add_to_favorites, name='add_to_favorites'),
    path("json/", show_json, name="show_json"),
    path("add_to_fav_flutter/<int:food_id>/<int:user_id>/", add_to_fav_flutter, name="add_to_fav_flutter")
]

sibuk/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user_auth/', include('user_auth.urls')),
    path('reviews/', include("reviews.urls")),  
    path('', include('recommended.urls')),
    path('favorites/', include('favfnd.urls')),
    path('api/foods/', include('foods.urls')),
    path('api/drinks/', include('drinks.urls'))
    ]

favfnd/models.py
from django.db import models
from django.db import models
from django.contrib.auth.models import User
from foods.models import Food
from drinks.models import Drink


# Create your models here.

class Favorite(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    merchant_area = models.CharField(max_length=255)
    merchant_name = models.CharField(max_length=255, )
    category = models.CharField(max_length=13)
    product = models.CharField(max_length=255, )
    description = models.CharField(max_length=255, )
    food = models.ManyToManyField(Food)
    drink = models.ManyToManyField(Drink)

favfnd/forms.py
from django import forms
from .models import Food
from .models import Drink

class FoodFilterForm(forms.Form):
    category = forms.CharField(required=False, widget=forms.TextInput(attrs={'placeholder': 'Nasi/Mie/Snack/Lainnya'}))

class DrinkFilterForm(forms.Form):
    category = forms.CharField(required=False, widget=forms.TextInput(attrs={'placeholder': 'Kopi/Nonkopi'}))

favfnd/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect, HttpResponse, HttpResponseNotFound, JsonResponse
from django.urls import reverse
from django.shortcuts import render
from django.core import serializers
from user_auth.models import UserProfile
from django.views.decorators.csrf import csrf_exempt
from .models import Drink
from .models import Food
from .forms import FoodFilterForm, DrinkFilterForm
from django.shortcuts import get_object_or_404
# Create your views here.

def show_favorites(request):
    if request.user.is_authenticated:
        return render(request, 'favorites.html')
    else :
        return redirect(reverse("user_auth:login"))

def show_favfood(request) :
    form = FoodFilterForm(request.GET)
    user = UserProfile.objects.filter(user=request.user).first()
    data_food = user.favfood.all()

    if form.is_valid() :
        category = form.cleaned_data.get("category")
        if category:
            data_food = data_food.filter(category=category)
        
    context = {
         "favfood": data_food,
    }
    return render(request, 'favorite_food.html', context)

def show_favdrink(request):
    form = DrinkFilterForm(request.GET)
    user = UserProfile.objects.filter(user=request.user).first()
    data_drink = user.favdrink.all()
    if form.is_valid() :
        category = form.cleaned_data.get("category")
        if category:
            data_drink = data_drink.filter(category=category)
    
    context = {
        "favdrink": data_drink
    }
    return render(request, 'favorite_drink.html', context)

   

@csrf_exempt
def filter_drink(request):
    category = request.GET.get('category', '')
    user = UserProfile.objects.filter(user=request.user).first()
    data_drinks = user.favdrink.all()
    if category:
        data_drinks = data_drinks.filter(category=category)
    drinks_json = serializers.serialize('json', data_drinks)
    print(category)
    return JsonResponse(drinks_json, safe=False)

@csrf_exempt
def filter_foods(request):
    category = request.GET.get('category', '')
    user = UserProfile.objects.filter(user=request.user).first()
    data_food = user.favfood.all()
    if category:
        data_food = data_food.filter(category=category)
    foods_json = serializers.serialize('json', data_food)
    return JsonResponse(foods_json, safe=False)

def show_json_favfood_by_user_id (request, user_id) :
    user = UserProfile.objects.filter(user=user_id).first()
    datafood = user.favfood.all()
    return HttpResponse(serializers.serialize("json", datafood), content_type="application/json")
     
def show_json_favdrink_by_user_id (request, user_id) :
    user = UserProfile.objects.filter(user=user_id).first()
    datafood = user.favdrink.all()
    return HttpResponse(serializers.serialize("json", datafood), content_type="application/json")
     
def remove_favdrink(request, drink_id):
    if request.method == "POST":
        if request.user.is_authenticated:
            user = UserProfile.objects.filter(user=request.user).first()
            try:
                drink = get_object_or_404(user.favdrink, id=drink_id)
                user.favdrink.remove(drink)
                return redirect('favfnd:show_favdrink')
            except Exception as e:
                print("Error:", e)
        else:
            print("User not authenticated")
    else:
        print("Invalid request method:", request.method)
    return JsonResponse({"success": False, "message": "Unauthorized or invalid request."}, status=403)

def remove_favfood(request, food_id):
    if request.method == "POST":
        if request.user.is_authenticated:
            user = UserProfile.objects.filter(user=request.user).first()
            try:
                food = get_object_or_404(user.favfood, id=food_id)
                user.favfood.remove(food)
                return redirect('favfnd:show_favfood')
            except Exception as e:
                print("Error:", e)
        else:
            print("User not authenticated")
    else:
        print("Invalid request method:", request.method)
    return JsonResponse({"success": False, "message": "Unauthorized or invalid request."}, status=403)

favfnd/templates/favorite_drink.html
{% extends 'base.html' %}
{% load static %}
{% block meta %}
		<title>Favorites | Dracarys</title>
{% endblock meta %}
{% block content %}
  <div class="favorite-drink-container">
    <div class="filter-box">
      <form
        id="filterForm"
        class="filter-form"
        method="GET"
      >
      <button type="submit" class="filter-btn" name="category" value="Kopi">
        <img src="{% static "images/category/coffe_icon.png" %}" class="filter-img" alt="">
        <span>Coffee</span>
      </button>
      <button type="submit" class="filter-btn" name="category" value="Non_Kopi">
        <img src="{% static "images/category/non_coffee_icon.png" %}" class="filter-img" alt="">
        <span>Non Coffee</span>
      </button>
      <button type="submit" class="filter-btn" name="" value="">
        <img src="{% static "images/category/no_filter_drink.png" %}" class="filter-img" alt="">
        <span>Remove Filter</span>
      </button>
      </form>
    </div>
    {% if favdrink  %}
    <div class="d-flex flex-wrap gap-4 justify-content-center mt-4">
      {% for item in favdrink %}
      <div class="card-box">
        <div class="card-box-inner shadow-sm" style="width: 100%;">
          <div class="card-box-front d-flex gap-4" style="justify-content: space-between;">
            <img
						{% if  item.category == "Kopi" %}
            	src="{% static  'images/category/coffe_icon.png' %}"
          	{% else %}
           		src="{% static 'images/category/non_coffee_icon.png' %}"
          	{% endif %}
              class="card-decoration"
              alt="card-decoration"
            />
            <div class="card-box-description">
              <h5 class="card-box-title mt-4">{{ item.product.title|truncatewords:2 }}</h5>
              <div>
                <p>{{ item.calories }} kcal</p>
                <p>{{ item.merchant_name|truncatewords:3 }}</p>
              </div>
              <div class="relative">
                <a
                  href="{% url 'drinks:drink_detail' item.pk %}"
                  class="btn btn-success"
                  style="background-color: #014d2f"
                >
                  See Details
                </a>
              </div>
            </div>
            <form action="{% url 'favfnd:remove_favdrink' item.id %}" method="POST" style="display: inline;">
              {% csrf_token %}
              <button type="submit" class="btn btn-danger" style="background: none; border: none;">
                  <i class="fas fa-trash" style="color: red; display: flex; justify-content: end;"></i> Hapus
              </button>
          </form>
                      
        </div>
          </div>
          
      </div>
      {% endfor %}
    </div>
    {% else %}
    <div class="empty-message">
      <h1 class="text-center">It looks like you don't have any favorite item</h1>
      <a class="text-center cata-link" href="{% url "drinks:show_drink" %}"><h1>Explore Catalogue</h1></a>
    </div>
    {% endif %}
  </div>
{% endblock content %}

favfnd/templates/favorite_food.html
{% extends 'base.html' %}
{% load static %}
{% block meta %}
		<title>Favorites | Dracarys</title>
{% endblock meta %}
{% block content %}
  <div class="favorite-food-container">
    <div class="filter-box">
      <form
        id="filterForm"
        class="filter-form"
        method="GET"
      >
        <button type="submit" class="filter-btn" name="category" value="Nasi">
          <img src="{% static "images/category/rice_icon.png" %}" class="filter-img" alt="">
          <span>Rice</span>
        </button>
        <button type="submit" class="filter-btn" name="category" value="Mie">
          <img src="{% static "images/category/noodle_icon.png" %}" class="filter-img" alt="">
          <span>Noodle</span>
        </button>
        <button type="submit" class="filter-btn" name="category" value="Snack">
          <img src="{% static "images/category/snack_icon.png" %}" class="filter-img" alt="">
          <span>Snack</span>
        </button>
        <button type="submit" class="filter-btn" name="category" value="Lainnya">
          <img src="{% static "images/category/other_icon.png" %}" class="filter-img" alt="">
          <span>Others</span>
        </button>
        <button type="submit" class="filter-btn" name="" value="">
          <img src="{% static "images/category/no_filter_food.png" %}" class="filter-img" alt="">
          <span>Remove Filter</span>
        </button>
      </form>
    </div>
    {% if favfood  %}
    <div class="d-flex flex-wrap gap-4 justify-content-center">
      {% for item in favfood %}
      <div class="card-box">
        <div class="card-box-inner shadow-sm">
          <div class="card-box-front d-flex gap-4">
            <img
            {% if item.category == "Nasi"  %}
              src="{% static  'images/category/rice_icon.png' %}"
            {% elif item.category == "Mie"  %}
              src="{% static  'images/category/noodle_icon.png' %}"
            {% elif item.category == "Snack"  %}
              src="{% static  'images/category/snack_icon.png' %}"
            {% elif item.category == "Lainnya"  %}
              src="{% static  'images/category/other_icon.png' %}"
            {% endif %}
              class="card-decoration"
              alt="card-decoration"
            />
            <div class="card-box-description">
              <h5 class="card-box-title mt-4">{{ item.product.title|truncatewords:2 }}</h5>
              <div>
                <p>{{ item.merchant_area.title }}</p>
                <p>{{ item.merchant_name|truncatewords:3 }}</p>
              </div>
              <div class="relative">
                <a
                  href="{% url 'foods:food_detail' item.pk %}"
                  class="btn btn-success"
                  style="background-color: #014d2f"
                >
                  See Details
                </a>
              </div>
            </div>
            <form action="{% url 'favfnd:remove_favfood' item.id %}" method="POST" style="display: inline;">
              {% csrf_token %}
              <button type="submit" class="btn btn-danger" style="background: none; border: none;">
                  <i class="fas fa-trash" style="color: red; display: flex; justify-content: end;"></i> Hapus
              </button>
          </form>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
    {% else %}
    <div class="empty-message">
      <h1 class="text-center">It looks like you don't have any favorite item</h1>
      <a class="text-center cata-link" href="{% url "foods:show_food" %}"><h1>Explore Catalogue</h1></a>
    </div>
    {% endif %}
  </div>
{% endblock content %}

favfnd/templates/favorites.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Favorites | Dracarys</title>
{% endblock meta %}

{% block content %}
    <div class="container-fluid favorite-container mx-auto my-4">
        <h2 class="hero-title text-center py-4">Explore Your Favorites</h2>
        <div class="d-flex justify-content-center gap-4">
            <a href="{% url "favfnd:show_favfood" %}" class="d-flex flex-column justify-content-center align-items-center fav-cata-item">
                <img src="{% static "images/category/rice_icon.png" %}" class="fav-cata-img" alt="">
                <span class="hero-title fs-2">Foods</span>
            </a>
            <a href="{% url "favfnd:show_favdrink" %}" class="d-flex flex-column justify-content-center align-items-center fav-cata-item">
                <img src="{% static "images/category/coffe_icon.png" %}" class="fav-cata-img" alt="">
                <span class="hero-title fs-2">Drinks</span>
            </a>            
        </div>
    </div>
{% endblock content %} 